<a href="https://colab.research.google.com/github/thriller-dev/CognoRise-Infotech/blob/main/Email_Spam_Naive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('/content/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [24]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [25]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [26]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

Train-Test

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.20)

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [29]:
X_train_cv.shape

(4457, 7802)

In [30]:
v.get_feature_names_out()[1771]

'checkboxes'

In [31]:
v.vocabulary_

{'well': 7515,
 'you': 7767,
 'told': 7001,
 'others': 5039,
 'marry': 4399,
 'them': 6875,
 'done': 2423,
 'call': 1626,
 'germany': 3139,
 'for': 2962,
 'only': 4987,
 'pence': 5180,
 'per': 5187,
 'minute': 4526,
 'from': 3040,
 'fixed': 2903,
 'line': 4150,
 'via': 7332,
 'access': 784,
 'number': 4894,
 '0844': 65,
 '861': 693,
 '85': 686,
 'no': 4830,
 'prepayment': 5416,
 'direct': 2346,
 'what': 7534,
 'is': 3776,
 'this': 6904,
 'hex': 3441,
 'place': 5261,
 'talk': 6750,
 'of': 4932,
 'explain': 2742,
 'me': 4438,
 'when': 7541,
 'finish': 2880,
 'then': 6878,
 'come': 1921,
 'pick': 5234,
 'the': 6867,
 'world': 7659,
 'most': 4625,
 'happiest': 3351,
 'frnds': 3033,
 'never': 4790,
 'have': 3377,
 'same': 5934,
 'characters': 1749,
 'dey': 2297,
 'just': 3909,
 'best': 1339,
 'understanding': 7200,
 'their': 6873,
 'differences': 2324,
 'your': 7770,
 '2004': 354,
 'account': 794,
 '07xxxxxxxxx': 48,
 'shows': 6179,
 '786': 631,
 'unredeemed': 7228,
 'points': 5317,
 'to': 

In [32]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [33]:
np.where(X_train_np[0]!=0)

(array([4399, 5039, 6875, 7001, 7515, 7767]),)

In [34]:
X_train_np[0][1771]

0

In [35]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [36]:
X_test_cv = v.transform(X_test)

In [37]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       961
           1       0.96      0.89      0.92       154

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [38]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])